// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWg9buUSnbAGKgejs5bJ-H5qb-oWbjflY',
    appId: '1:154149331628:web:ee9655d88b5c71a2813509',
    messagingSenderId: '154149331628',
    projectId: 'savery-5f977',
    authDomain: 'savery-5f977.firebaseapp.com',
    storageBucket: 'savery-5f977.firebasestorage.app',
    measurementId: 'G-HYFN33Z2RY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNk21ueKJ__0VxhAhIhm1U3amtpa1WRaI',
    appId: '1:154149331628:android:a340f3a22f595476813509',
    messagingSenderId: '154149331628',
    projectId: 'savery-5f977',
    storageBucket: 'savery-5f977.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiN2wzjM1OBJZ1MR2hMHz-_UWxG1dKuOU',
    appId: '1:154149331628:ios:7f3d05b49dbb8393813509',
    messagingSenderId: '154149331628',
    projectId: 'savery-5f977',
    storageBucket: 'savery-5f977.firebasestorage.app',
    androidClientId: '154149331628-rfouoodcdj4o7u5q232gg3a4bf6nttls.apps.googleusercontent.com',
    iosClientId: '154149331628-k295arbeb6g3nfnb37fte7m5k6i92lj4.apps.googleusercontent.com',
    iosBundleId: 'com.example.savery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiN2wzjM1OBJZ1MR2hMHz-_UWxG1dKuOU',
    appId: '1:154149331628:ios:7f3d05b49dbb8393813509',
    messagingSenderId: '154149331628',
    projectId: 'savery-5f977',
    storageBucket: 'savery-5f977.firebasestorage.app',
    androidClientId: '154149331628-rfouoodcdj4o7u5q232gg3a4bf6nttls.apps.googleusercontent.com',
    iosClientId: '154149331628-k295arbeb6g3nfnb37fte7m5k6i92lj4.apps.googleusercontent.com',
    iosBundleId: 'com.example.savery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWg9buUSnbAGKgejs5bJ-H5qb-oWbjflY',
    appId: '1:154149331628:web:1dd9970a212def33813509',
    messagingSenderId: '154149331628',
    projectId: 'savery-5f977',
    authDomain: 'savery-5f977.firebaseapp.com',
    storageBucket: 'savery-5f977.firebasestorage.app',
    measurementId: 'G-X3W7298PCL',
  );

}