// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCljHiWLKs3fmzCkDN3w3VsqOnQ08rZF_w',
    appId: '1:26297828009:web:6b88516d371218f6dedfb8',
    messagingSenderId: '26297828009',
    projectId: 'savery-d54a9',
    authDomain: 'savery-d54a9.firebaseapp.com',
    storageBucket: 'savery-d54a9.firebasestorage.app',
    measurementId: 'G-YQCQKGLB3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcZZ7ihjd0zLZJktSZ3F86lEnCOmZzinI',
    appId: '1:26297828009:android:cd713cc7f8788fa7dedfb8',
    messagingSenderId: '26297828009',
    projectId: 'savery-d54a9',
    storageBucket: 'savery-d54a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtLSo8ax3wMw5C0kjcwcsbhtLahsDelqM',
    appId: '1:26297828009:ios:3a6c286a3273e69adedfb8',
    messagingSenderId: '26297828009',
    projectId: 'savery-d54a9',
    storageBucket: 'savery-d54a9.firebasestorage.app',
    iosBundleId: 'com.example.savery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtLSo8ax3wMw5C0kjcwcsbhtLahsDelqM',
    appId: '1:26297828009:ios:3a6c286a3273e69adedfb8',
    messagingSenderId: '26297828009',
    projectId: 'savery-d54a9',
    storageBucket: 'savery-d54a9.firebasestorage.app',
    iosBundleId: 'com.example.savery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCljHiWLKs3fmzCkDN3w3VsqOnQ08rZF_w',
    appId: '1:26297828009:web:dfdc8e87a2b945cbdedfb8',
    messagingSenderId: '26297828009',
    projectId: 'savery-d54a9',
    authDomain: 'savery-d54a9.firebaseapp.com',
    storageBucket: 'savery-d54a9.firebasestorage.app',
    measurementId: 'G-NXZ7BS0LKT',
  );
}
